<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>SchoolManagement.Bootstrap.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolManagement.Application\SchoolManagement.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

</Project>
