<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>ERP Scolaire RDC</Authors>
    <Company>School Management</Company>
    <Product>ERP Administration Scolaire</Product>
  </PropertyGroup>
</Project>
