// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Bootstrap.API.Persistence;

#nullable disable

namespace SchoolManagement.Bootstrap.API.Persistence.Migrations
{
    [DbContext(typeof(BootstrapDbContext))]
    [Migration("20260810112005_BootstrapSchoolRegistryFoundation")]
    partial class BootstrapSchoolRegistryFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapEstablishmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("DeviceId", "Status")
                        .HasDatabaseName("IX_Session_Device_Status");

                    b.ToTable("BootstrapEstablishmentSessions", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolEstablishmentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CredentialVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_EstablishmentCredential_Active")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("SchoolId", "CredentialVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_EstablishmentCredential_SchoolId_Version");

                    b.ToTable("BootstrapSchoolEstablishmentCredentials", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CloudBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("KeyVersion")
                        .HasColumnType("int");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicKeyFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ServerInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_BootstrapSchoolRegistry_IsActive");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_BootstrapSchoolRegistry_SchoolId");

                    b.ToTable("BootstrapSchoolRegistry", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapEstablishmentSession", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolEstablishmentCredential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", "School")
                        .WithMany("Sessions")
                        .HasForeignKey("SchoolId")
                        .HasPrincipalKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolEstablishmentCredential", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", "School")
                        .WithMany("Credentials")
                        .HasForeignKey("SchoolId")
                        .HasPrincipalKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
