// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Bootstrap.API.Persistence;

#nullable disable

namespace SchoolManagement.Bootstrap.API.Persistence.Migrations
{
    [DbContext(typeof(BootstrapDbContext))]
    partial class BootstrapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapEstablishmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("DeviceId", "Status")
                        .HasDatabaseName("IX_Session_Device_Status");

                    b.ToTable("BootstrapEstablishmentSessions", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolEstablishmentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CredentialVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_EstablishmentCredential_Active")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("SchoolId", "CredentialVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_EstablishmentCredential_SchoolId_Version");

                    b.ToTable("BootstrapSchoolEstablishmentCredentials", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CloudBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("KeyVersion")
                        .HasColumnType("int");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicKeyFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ServerInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_BootstrapSchoolRegistry_IsActive");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_BootstrapSchoolRegistry_SchoolId");

                    b.ToTable("BootstrapSchoolRegistry", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateAgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CredentialVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_UpdateAgentCredential_Active")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("SchoolId", "CredentialVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_UpdateAgentCredential_SchoolId_Version");

                    b.ToTable("UpdateAgentCredential", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateRelease", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FromSchemaVersion")
                        .HasColumnType("int");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<string>("MinimumApiVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MinimumDesktopVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ReleaseId");

                    b.HasIndex("Channel", "Status")
                        .HasDatabaseName("IX_UpdateRelease_Channel_Status");

                    b.HasIndex("Channel", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_UpdateRelease_Channel_Version");

                    b.ToTable("UpdateRelease", null, t =>
                        {
                            t.HasCheckConstraint("CK_UpdateRelease_Channel", "[Channel] IN (N'DEV', N'PROD')");

                            t.HasCheckConstraint("CK_UpdateRelease_SchemaRange", "[FromSchemaVersion] >= 1 AND [SchemaVersion] >= [FromSchemaVersion]");

                            t.HasCheckConstraint("CK_UpdateRelease_Status", "[Status] IN (N'Draft', N'Published', N'Blocked')");
                        });
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateReleaseArtifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Signature")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ArtifactId");

                    b.HasIndex("ReleaseId", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_UpdateReleaseArtifact_Release_Type");

                    b.ToTable("UpdateReleaseArtifact", null, t =>
                        {
                            t.HasCheckConstraint("CK_UpdateReleaseArtifact_Sha256", "LEN([Sha256]) = 64 AND [Sha256] NOT LIKE N'%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_UpdateReleaseArtifact_Type", "[Type] IN (N'Desktop', N'Api', N'Migration', N'Mobile')");
                        });
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateReleaseTarget", b =>
                {
                    b.Property<Guid>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TargetId");

                    b.HasIndex("ReleaseId")
                        .IsUnique()
                        .HasDatabaseName("UX_UpdateReleaseTarget_Release_Global")
                        .HasFilter("[SchoolId] IS NULL");

                    b.HasIndex("SchoolId");

                    b.HasIndex("ReleaseId", "SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_UpdateReleaseTarget_Release_School")
                        .HasFilter("[SchoolId] IS NOT NULL");

                    b.ToTable("UpdateReleaseTarget", (string)null);
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapEstablishmentSession", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolEstablishmentCredential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", "School")
                        .WithMany("Sessions")
                        .HasForeignKey("SchoolId")
                        .HasPrincipalKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolEstablishmentCredential", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", "School")
                        .WithMany("Credentials")
                        .HasForeignKey("SchoolId")
                        .HasPrincipalKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateAgentCredential", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .HasPrincipalKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateReleaseArtifact", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateRelease", "Release")
                        .WithMany("Artifacts")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateReleaseTarget", b =>
                {
                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateRelease", "Release")
                        .WithMany("Targets")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .HasPrincipalKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Release");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.BootstrapSchoolRegistryEntry", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SchoolManagement.Bootstrap.API.Persistence.Entities.UpdateRelease", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
