<#
.SYNOPSIS
  Genere le fichier .env Docker a partir de ServeurDonneesCloud.txt (PC ecole).
  Le mot de passe DPAPI est dechiffre localement et n'est pas affiche.

.EXAMPLE
  .\scripts\prepare-docker-env.ps1
#>
param(
    [string]$ApiDir = "",
    [string]$OutFile = "",
    [int]$ApiHostPort = 8080
)

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")

if ([string]::IsNullOrWhiteSpace($ApiDir)) {
    $ApiDir = Join-Path $root "src\SchoolManagement.API\bin\Debug\net8.0"
}
if (-not (Test-Path $ApiDir)) {
    throw "API directory not found: $ApiDir - start the local API once first."
}
$ApiDir = (Resolve-Path $ApiDir).Path

$cloudFile = Join-Path $ApiDir "ServeurDonneesCloud.txt"
if (-not (Test-Path $cloudFile)) {
    throw "Missing file: $cloudFile - run scripts\configure-cloud-sync.ps1 first."
}

if ([string]::IsNullOrWhiteSpace($OutFile)) {
    $OutFile = Join-Path $root ".env"
}

$tempCs = Join-Path $env:TEMP "erp-prepare-docker-env.cs"
$tempExe = Join-Path $env:TEMP "erp-prepare-docker-env.exe"

$cs = @'
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

class Program {
  static int Main(string[] args) {
    var cloudPath = args[0];
    var outPath = args[1];
    var apiPort = args[2];

    var lines = File.ReadAllLines(cloudPath);
    string server = null, database = null, user = null, encPwd = null;
    var port = 1433;
    foreach (var raw in lines) {
      var line = raw.Trim();
      if (line.Length == 0 || line.StartsWith("#")) continue;
      var i = line.IndexOf('=');
      if (i <= 0) continue;
      var key = line.Substring(0, i).Trim().ToUpperInvariant();
      var val = line.Substring(i + 1).Trim();
      switch (key) {
        case "SERVEUR": server = val; break;
        case "PORT": int.TryParse(val, out port); break;
        case "BASE": database = val; break;
        case "UTILISATEUR": user = val; break;
        case "MOTDEPASSE": encPwd = val; break;
      }
    }
    if (string.IsNullOrWhiteSpace(server) || string.IsNullOrWhiteSpace(database) ||
        string.IsNullOrWhiteSpace(user) || string.IsNullOrWhiteSpace(encPwd)) {
      Console.Error.WriteLine("ServeurDonneesCloud.txt incomplete.");
      return 2;
    }

    // Mirror EncryptionService (DPAPI LocalMachine + entropy)
    var entropy = Encoding.UTF8.GetBytes("SchoolManagement.ERP.Scolaire.RDC.v1");
    const string prefix = "ENC:";
    if (!encPwd.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) {
      Console.Error.WriteLine("Password is not DPAPI-encrypted (ENC:).");
      return 3;
    }
    var protectedBytes = Convert.FromBase64String(encPwd.Substring(prefix.Length));
    var plainBytes = ProtectedData.Unprotect(protectedBytes, entropy, DataProtectionScope.LocalMachine);
    var pwd = Encoding.UTF8.GetString(plainBytes);

    string jwt;
    string aes;
    using (var rng = new RNGCryptoServiceProvider()) {
      var buf = new byte[48];
      rng.GetBytes(buf);
      jwt = Convert.ToBase64String(buf).TrimEnd('=').Replace('+', 'x').Replace('/', 'y');
      buf = new byte[32];
      rng.GetBytes(buf);
      aes = Convert.ToBase64String(buf).TrimEnd('=').Replace('+', 'x').Replace('/', 'y');
    }
    var cs = "Server=" + server + "," + port + ";Database=" + database + ";User Id=" + user +
             ";Password=" + pwd + ";TrustServerCertificate=True;Encrypt=True";

    var sb = new StringBuilder();
    sb.AppendLine("# Generated by scripts/prepare-docker-env.ps1 - DO NOT COMMIT");
    sb.AppendLine("API_HOST_PORT=" + apiPort);
    sb.AppendLine("SQL_CONNECTION_STRING=" + cs);
    sb.AppendLine("JWT_SECRET_KEY=" + jwt);
    sb.AppendLine("JWT_ISSUER=SchoolManagementRDC");
    sb.AppendLine("JWT_AUDIENCE=SchoolManagementClients");
    sb.AppendLine("ERP_CONFIG_ENCRYPTION_KEY=" + aes);
    sb.AppendLine("CORS_ORIGIN=*");
    sb.AppendLine("MSSQL_SA_PASSWORD=Your_strong_Password123");
    sb.AppendLine("SQL_HOST_PORT=1433");
    File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
    Console.WriteLine("OK");
    Console.WriteLine("OUT=" + outPath);
    Console.WriteLine("SQL_SERVER=" + server);
    Console.WriteLine("SQL_DATABASE=" + database);
    Console.WriteLine("SQL_USER=" + user);
    return 0;
  }
}
'@

Set-Content -Path $tempCs -Value $cs -Encoding ASCII

$csc = Join-Path $env:WINDIR "Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) {
    throw "csc.exe not found"
}
& $csc /nologo /out:$tempExe $tempCs | Out-Null
if (-not (Test-Path $tempExe)) {
    throw "Failed to compile prepare-docker-env helper"
}

$prev = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$output = & $tempExe $cloudFile $OutFile $ApiHostPort 2>&1
$exit = $LASTEXITCODE
$ErrorActionPreference = $prev

Remove-Item $tempCs, $tempExe -Force -ErrorAction SilentlyContinue

if ($exit -ne 0) {
    $output | ForEach-Object { Write-Host $_ }
    throw "Failed to generate .env (exit $exit)"
}

$output | ForEach-Object { Write-Host $_ }
Write-Host ""
Write-Host "File .env ready (SQL password included locally, not printed)."
Write-Host "Next: install Docker on the VPS, then: docker compose up -d --build"
Write-Host "Guide: docs\deploy-docker-cloud.md"
